### ISSUE TITLE
[dev] Add build system, fix release error

### ISSUE THREAD

**Issue by makukha** [makukha/caseutil#60]
Add
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
```
to fix
```
error: Failed to publish `dist/caseutil-0.7.1-py3-none-any.whl` to https://upload.pypi.org/legacy/
  Caused by: Upload failed with status code 400 Bad Request. Server says: 400 license-file introduced in metadata version 2.4, not 2.1. See https://packaging.python.org/specifications/core-metadata for more information.
```
